# Generated by Django 4.2.21 on 2025-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jawaban_a', models.CharField(max_length=255)),
                ('jawaban_b', models.CharField(max_length=255)),
                ('jawaban_c', models.CharField(max_length=255)),
                ('jawaban_d', models.CharField(max_length=255)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
