# Generated by Django 4.2.21 on 2025-06-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kuis', models.CharField(max_length=255)),
                ('waktu_mulai', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('skor', models.IntegerField(default=0)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuis.kuis')),
            ],
        ),
        migrations.AddField(
            model_name='soal',
            name='kuis',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soal_set', to='kuis.kuis'),
        ),
    ]
