# Generated by Django 4.2.21 on 2025-06-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0002_kuis_peserta_soal_kuis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='kuis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soal_set', to='kuis.kuis'),
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuis.peserta')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuis.soal')),
            ],
        ),
    ]
