# Generated by Django 4.2.21 on 2025-06-05 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0003_alter_soal_kuis_jawaban'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1)),
                ('benar', models.BooleanField(default=False)),
                ('waktu_dijawab', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuis.peserta')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuis.soal')),
            ],
        ),
        migrations.DeleteModel(
            name='Jawaban',
        ),
    ]
